#The combination of functions defined below are used together to invert
#a matrix and then store the inverted matrix in cache memory for easy access

#This first function takes a square matrix as an argument and creates a list.
#One of the list element will become the cached matrix

makeCacheMatrix<-function(x=matrix()){
	m<-NULL 
	set<-function(y){
		x<<-y #Set the matrix m to the agument passed through the set function
		m<<-NULL
	}
	get<-function() x  #Function passed to the output variable list
	setInverse<-function(solve) m<<-solve #m is the solve function and is passed to the output variable list
	getInverse<-function() m #In solve function passed to the output variable list
	list(set = set, get = get,
		setInverse=setInverse,
		getInverse = getInverse) #This is the output list of the cache function
}

#This second function takes the output generated by the makeCacheMatrix function
#and generates the inverse matrix, the first pass through the data, or retrieves
#the cached matrix on subsequent calls to this function.

cacheSolve<-function(x,...){ #Input is created by makeCacheMatrix function and is a list
	m<-x$getInverse()
	if(!is.null(m)){ #you enter this loop if the inverse is cached
		message("getting cached inverse")
		return(m) #if the inverse hase been calculated you will exit the function here.
	}
	data<-x$get()
	m<-solve(data,...)  #The first pass through the data and this call will create the matrix inverse
	x$setInverse(m)
	m
}

